"""Pydantic models for Anamnesis — internal data structures and API schemas."""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ── Enums ──

class ContentType(str, Enum):
    FACT = "fact"
    DECISION = "decision"
    OBSERVATION = "observation"
    INSTRUCTION = "instruction"
    EVENT = "event"


class Authority(str, Enum):
    EXPLICIT = "explicit"      # User/Kali stated directly
    INFERRED = "inferred"      # AI derived from context
    SYSTEM = "system"          # Auto-generated by system


class MemoryStatus(str, Enum):
    ACTIVE = "active"
    DECAYED = "decayed"
    ARCHIVED = "archived"
    SUPERSEDED = "superseded"


class SynthesisStyle(str, Enum):
    FACTUAL = "factual"
    STRATEGIC = "strategic"
    NARRATIVE = "narrative"


# ── Memory Bank ──

class BankCreate(BaseModel):
    name: str
    mission: str
    directives: list[str] = Field(default_factory=list)
    disposition: str = "balanced"
    weight_factors: dict[str, float] = Field(default_factory=lambda: {
        "semantic": 0.30,
        "temporal": 0.20,
        "relational": 0.20,
        "strategic": 0.30,
    })
    default_decay_days: int = 90


class BankUpdate(BaseModel):
    mission: Optional[str] = None
    directives: Optional[list[str]] = None
    disposition: Optional[str] = None
    weight_factors: Optional[dict[str, float]] = None
    default_decay_days: Optional[int] = None


class BankResponse(BaseModel):
    id: str
    name: str
    mission: str
    directives: list[str]
    disposition: str
    weight_factors: dict[str, float]
    default_decay_days: int
    created_at: datetime
    updated_at: datetime
    memory_count: int = 0
    entity_count: int = 0


# ── Retain ──

class RetainRequest(BaseModel):
    bank: str
    content: str
    content_type: ContentType = ContentType.FACT
    source: str = "unknown"
    reasoning: Optional[str] = None
    authority: Authority = Authority.INFERRED
    confidence: float = 0.8
    decay_condition: Optional[str] = None
    tags: list[str] = Field(default_factory=list)
    supersedes: list[str] = Field(default_factory=list)
    depends_on: list[str] = Field(default_factory=list)


class ExtractedFact(BaseModel):
    subject: str
    predicate: str
    object: str


class RetainResponse(BaseModel):
    memory_id: str
    extracted_facts: list[ExtractedFact]
    entities_linked: list[str]
    weight: float
    weight_note: str = ""


# ── Recall ──

class RecallFilters(BaseModel):
    content_types: Optional[list[ContentType]] = None
    min_weight: Optional[float] = None
    status: MemoryStatus = MemoryStatus.ACTIVE
    tags: Optional[list[str]] = None
    after: Optional[datetime] = None
    before: Optional[datetime] = None


class RecallRequest(BaseModel):
    bank: str
    query: str
    limit: int = 10
    filters: Optional[RecallFilters] = None
    dimension_weights: Optional[dict[str, float]] = None  # Override bank defaults


class DimensionScores(BaseModel):
    semantic: float = 0.0
    temporal: float = 0.0
    relational: float = 0.0
    strategic: float = 0.0


class RecalledMemory(BaseModel):
    id: str
    content: str
    content_type: ContentType
    score: float
    dimension_scores: DimensionScores
    weight: float
    confidence: float
    reasoning: Optional[str] = None
    authority: Authority
    source: str
    tags: list[str]
    created_at: datetime
    last_accessed_at: datetime


class RecallResponse(BaseModel):
    memories: list[RecalledMemory]
    total_candidates: int
    retrieval_time_ms: float


# ── Reflect ──

class ReflectRequest(BaseModel):
    bank: str
    question: str
    context: Optional[str] = None
    max_memories: int = 20
    synthesis_style: SynthesisStyle = SynthesisStyle.STRATEGIC


class ReflectResponse(BaseModel):
    synthesis: str
    cited_memories: list[str]
    confidence: float
    gaps_identified: list[str]


# ── Decay Check ──

class DecayCheckRequest(BaseModel):
    bank: str


class DecayCheckResponse(BaseModel):
    decayed_count: int
    decayed_ids: list[str]
    next_check: Optional[datetime] = None


# ── Reweight ──

class ReweightRequest(BaseModel):
    bank: str
    trigger_event: Optional[str] = None


class ReweightResponse(BaseModel):
    updated_count: int
    weight_stats: dict[str, float]  # mean, median, min, max


# ── Bulk Retain ──

class BulkRetainRequest(BaseModel):
    memories: list[RetainRequest]


class BulkRetainResponse(BaseModel):
    retained_count: int
    memory_ids: list[str]
    errors: list[str] = Field(default_factory=list)


# ── Export / Import ──

class ExportResponse(BaseModel):
    version: str = "1.0"
    exported_at: datetime
    banks: list[dict]


class ImportRequest(BaseModel):
    data: dict
    merge: bool = False


class ImportResponse(BaseModel):
    imported_banks: int = 0
    imported_memories: int = 0
    imported_entities: int = 0
    imported_relationships: int = 0
    skipped_memories: int = 0
    skipped_entities: int = 0
    errors: list[str] = Field(default_factory=list)


# ── Health ──

class HealthResponse(BaseModel):
    status: str = "ok"
    version: str = "0.1.0"
    db_connected: bool = False
    embedding_configured: bool = False
    llm_configured: bool = False
    memory_count: int = 0
    bank_count: int = 0
